version: '3.8'
name: o3-waf-example

services:
  ai_model:
    build: ./MODEL_SERVE/
    ports:
      - "8500:8500"
      - "8501:8501"

  reporter:
    build: ./REPORTER/
    environment:
      DB: mongo
      # OPENAI_API_KEY: "<YOUR_KEY>"
    depends_on:
      - mongo

  waf_edge:
    build: ./WAF_EDGE/
    ports:
      - "5050:5050"
    environment:
      ATTACKER_REPONSE_MODE: dissconnect
      SERVER: app
      SERVER_PORT: 8080
      FAKE_SERVER: fake_app
      FAKE_SERVER_PORT: 8081
      REDIS_HOST: redis
    depends_on:
      - db
      - app
      - fake_db
      - fake_app
      - ai_model
      - mongo
      - redis

  waf_db_protector:
    build: ./WAF_DB_PROTECTOR/
    ports:
      - "5051:5051"
    environment:
      PORT: 5051

      REDIS_HOST: redis

      MYSQL_HOST: db
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_DB: doc_app
      MYSQL_PORT: 3306

      FAKE_MYSQL_HOST: fake_db
      FAKE_MYSQL_USER: your_username
      FAKE_MYSQL_PASSWORD: your_password
      FAKE_MYSQL_DB: doc_app
      FAKE_MYSQL_PORT: 3307
    depends_on:
      - db
      - fake_db
      - ai_model
      - mongo
      - redis

  faker:
    build: ./FAKER/
    environment:
      MYSQL_HOST: db
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_DB: doc_app
      MYSQL_PORT: 3306

      FAKE_MYSQL_HOST: fake_db
      FAKE_MYSQL_USER: your_username
      FAKE_MYSQL_PASSWORD: your_password
      FAKE_MYSQL_DB: doc_app
      FAKE_MYSQL_PORT: 3307

    depends_on:
      - db
      - fake_db
      - waf_db_protector

  app:
    build: ./APP/
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_PROXY_PORT: 5051
      DB_PROXY: waf_db_protector
    depends_on:
      - waf_db_protector

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: doc_app
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"

  fake_app:
    build: ./APP/
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_PROXY_PORT: 5051
      DB_PROXY: waf_db_protector
    depends_on:
      - waf_db_protector

  fake_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: doc_app
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
